### PR TITLE
Use template variables to expand variables in promQL expressions

### PR DESCRIPTION
**Pull request by wuzuf**
Another solution to the problem shared in https://github.com/grafana/dashboard-linter/pull/18
Tested successfully on the HEAD of https://github.com/kubernetes-monitoring/kubernetes-mixin.git (removing the `sed` line in the Makefile)
@tomwilkie  @arajkumar

### CODE REVIEW

**Review by arajkumar — COMMENTED** [review]
Overall fix looks good to me.

**Comment by tomwilkie** [comment]
Oh I like this approach!  One qq: how does this avoid expanding $job and $instance variables (for the other lint check?)

**Comment by wuzuf** [comment]
> Oh I like this approach! One qq: how does this avoid expanding $job and $instance variables (for the other lint check?)

In fact this does not change the fact that the variables are not expanded if found between double quotes. So $job will stay $job in this context.
Though I feel that it is not very intuitive, and we probably need to have an option added to the `expandVariables` function, in order to control that behavior. This way it will be clear in the linter itself, what kind of substitution we are using (and again, still having in mind that we would be able to detect variables that are not defined :)).
I could contribute something like that:
```
type VariablesExpander struct {
    ExpandInsideQuotes bool
    ErrorWhenUndefined bool
    Variables []Template
    [...]
}

func (expander *VariablesExpander) Expand(s string) (string, error) {
    [...]
}
```
Let me know what you think, I can make another PR for that.

**Comment by wuzuf** [comment]
Rebase done!

**Comment by tomwilkie** [comment]
Thank you @wuzuf!

**Pull request merged**
