### PR TITLE
Allow multiple data sources, of different types. Still enforce best-practice naming.

### LINKED ISSUE #14: Datasource selection priority
In reviewing korfuri/django-prometheus#318 I noticed a couple of things.

1. The `panel-datasource-rule` is very specific about the panel types it checks (`graph`, `singlestat`, and `table`) and therefore excluded `timeseries`. I've created #13 for this.
2. The django dashboard actually sets the datasource on each target for the panel, rather than once on the panel itself. Both are "technically" valid. Should the panel-datasource rule accommodate this case, or should we be opinionated that different datasources on targets for the same panel is an anti-pattern? I believe that we should consider it an anti-pattern, and that there should be a target specific rule to check for it.

Thoughts @tomwilkie ?

### PR DESCRIPTION
**Pull request by rgeyer**
This adds the flexibility in data source naming which is discussed in #14.

Specifically, if a dashboard has only one data source, it may have the name/uid `datasource` or `<type>_datasource`, and it may have the label "Data Source" or "<Title(type)> Data Source".

This also ensures that when more than one data source is present on the dashboard, the more specific name is no longer optional, but required.

Also, this tweaks the `template-job-rule` and `template-instance-rule` to allow for either form of the prometheus data source UID/name.

Finally, this tweaks the `panel-datasource-rule` to allow the use of any data source which is actually defined on the dashboard, rather than only checking for `$datasource` and `${datasource}`.

Resolves #14 and supersedes #101 and #40

### CODE REVIEW

**Review by StefanKurek — COMMENTED** [review]
Looks good as far as I can tell. Didn't take the full time to read through the supporting code to fully understand the effects of the changes, so just commenting rather than approving 😄 . Will be nice to get rid of some of the linter exceptions for sure.

**Review by schmikei — COMMENTED** [review]
This looks pretty good! I think that we'll run into quite a few misnames of Prometheus Data Source && Loki Data Source once this gets incorporated.

i.e. a lot of mixing and matching Loki Datasource && Data Source from a quick scan.

Was just curious is the `Data Source` supposed to be capitalized or is it supposed to be sentence case in the UI element if we are following this guideline? 
https://grafana.com/docs/writers-toolkit/style-guide/ux-writing/#use-sentence-case-in-ui-elements

I'll defer to you but I was just curious for my own sake of knowledge :)

**Comment by rgeyer** [comment]
> Was just curious is the `Data Source` supposed to be capitalized or is it supposed to be sentence case in the UI element if we are following this guideline? https://grafana.com/docs/writers-toolkit/style-guide/ux-writing/#use-sentence-case-in-ui-elements
> 
> I'll defer to you but I was just curious for my own sake of knowledge :)

Ahh, good point, it *may* be properly `Data source` given that standard.

I'll check with our docs/standards team to be sure. Thanks for the heads-up, and for giving it a look!

**Comment by JonathanWamsley** [comment]
Screenshot 2023-04-27 at 3 36 25 PM
There also seems to be some linting inconsistencies with `job`  wanting to be lowercased too while others seem to be fine.

**Comment by rgeyer** [comment]
> Screenshot 2023-04-27 at 3 36 25 PM There also seems to be some linting inconsistencies with `job` wanting to be lowercased too while others seem to be fine.

Yeah, `job` and `instance` have always had a rule which requires them to be lower case.

Which... Does seem a bit inconsistent. I'll have to think through this. I'd rather not change it outrightly, since that would cause sudden failures for anyone who's been following the rules as-is.

But I think you're right, in the spirit of sentence casing, those labels should probably be capitalized.

**Comment by rgeyer** [comment]
In the most recent commit, I actually make a couple of changes which should promote backward compatibility, and ease the move forward.

For one, since the formatting of the labels for data sources have changed, this is downgraded to a warning. In a future version (we don't have a canonical version for the linter yet, but maybe at 1.0?), we can change this back to an error.

Also, title casing for Job and Instance are actually correct on the label, so the rule enforces that now. However, for those who were using the dashboard-linter previously, and may have labeled all of their job and instance templates in lower case, the rule is now a Warning when it's violated, which should allow an easier transition.

This probably also warrants a changelog of sorts for the dashboard-linter, so that these sorts of changes/compromises can be documented.

**Review by v-zhuravlev — APPROVED** [review]
Well thought out! LGTM

**Pull request merged**
