### PR TITLE
Update prometheus

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@o11y.eu>

### CODE REVIEW

**Comment by tomwilkie** [comment]
This is a massive improvement, thank you so much @roidelapluie ❤️

**Review by rgeyer — CHANGES_REQUESTED** [review]
Looks like the tests caught some modules which weren't in the go.sum.

Can you run a `go mod tidy` in your branch, and commit the result. Happy to approve and merge at that point.

Thank you!

**Comment by roidelapluie** [comment]
Done

**Review by rgeyer — APPROVED** [review]

**Comment by rgeyer** [comment]
> Done

Thank you for the contribution!

**Pull request merged**
